// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MI.DBContext.Models;

public partial class AOrganize
{
    public Guid Id { get; set; }

    public string OrganizeName { get; set; }

    public string Tel { get; set; }

    public string Locaion { get; set; }

    public Guid ParentId { get; set; }

    public Guid CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime LastUpdatedDate { get; set; }

    public Guid LastUpdatedUserId { get; set; }
}