// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MI.DBContext.Models;

public partial class AProfile
{
    public Guid UserId { get; set; }

    public string UserName { get; set; }

    public string FullName { get; set; }

    public string EmployeeCode { get; set; }

    public Guid? DepartmentId { get; set; }

    public Guid OrganizeId { get; set; }

    /// <summary>
    /// Mật khẩu
    /// </summary>
    public string Password { get; set; }

    public string Salt { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsDisabled { get; set; }

    public int? FailedPasswordAttemptCount { get; set; }

    public bool? IsLockedOut { get; set; }

    public DateTime? IsLockedOutTime { get; set; }

    public Guid CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime LastUpdatedDate { get; set; }

    public Guid LastUpdatedUserId { get; set; }
}