// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MI.DBContext.Models;

public partial class EClassLearningLog
{
    public Guid Id { get; set; }

    public Guid ClassLearningId { get; set; }

    public Guid ClassUserId { get; set; }

    public Guid ClassContentId { get; set; }

    public DateTime LogTime { get; set; }

    public string ActionCode { get; set; }

    public Guid CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime LastUpdatedDate { get; set; }

    public Guid LastUpdatedUserId { get; set; }
}