// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MI.DBContext.Models;

public partial class EClassContent
{
    public Guid Id { get; set; }

    public Guid ClassId { get; set; }

    public string Title { get; set; }

    public string FileId { get; set; }

    public int ContentType { get; set; }

    public DateTime? StartTime { get; set; }

    public int? EndTime { get; set; }

    public bool IsActive { get; set; }

    public bool IsRequired { get; set; }

    public int? OrderNum { get; set; }

    public string Description { get; set; }

    public Guid CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime LastUpdatedDate { get; set; }

    public Guid LastUpdatedUserId { get; set; }
}