// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MI.DBContext.Models;

public partial class EClass
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Thumbnail { get; set; }

    public Guid? CateId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public int TypeId { get; set; }

    public int PublicId { get; set; }

    public int RegisterId { get; set; }

    public int StatusId { get; set; }

    public Guid? CertificationId { get; set; }

    public int? CertificationType { get; set; }

    public Guid CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime LastUpdatedDate { get; set; }

    public Guid LastUpdatedUserId { get; set; }
}