// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MI.DBContext.Models;

public partial class EclassLearning
{
    public Guid Id { get; set; }

    public Guid ClassId { get; set; }

    public Guid ClassUserId { get; set; }

    public Guid ClassContentId { get; set; }

    public int? Times { get; set; }

    public decimal? LearnTime { get; set; }

    public decimal? LearnScore { get; set; }

    public bool IsFinished { get; set; }

    public string LastState { get; set; }

    public Guid CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime LastUpdatedDate { get; set; }

    public Guid LastUpdatedUserId { get; set; }
}