// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MI.DBContext.Models;

public partial class TtestAnswer
{
    public Guid Id { get; set; }

    public Guid QuestionId { get; set; }

    public string Answer { get; set; }

    public bool IsCheck { get; set; }

    public int OrderNum { get; set; }

    public int Mark { get; set; }

    public Guid CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime LastUpdatedDate { get; set; }

    public Guid LastUpdatedUserId { get; set; }
}