// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MI.DBContext.Models;

public partial class TtestForm
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public Guid CateId { get; set; }

    public int QuestionNum { get; set; }

    /// <summary>
    /// Thang điểm: NULL &lt;=&gt; Thông thường.
    /// </summary>
    public int GradeScaleId { get; set; }

    public bool IsSoap { get; set; }

    public bool IsSoapAnswer { get; set; }

    public int Status { get; set; }

    public Guid CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime LastUpdatedDate { get; set; }

    public Guid LastUpdatedUserId { get; set; }
}