// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MI.DBContext.Models;

public partial class TtestInfo
{
    public Guid Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Thumbnail { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public int RegistrationType { get; set; }

    public int ResultType { get; set; }

    public int Attempts { get; set; }

    public decimal MinScore { get; set; }

    public Guid? TestFormId { get; set; }

    public string SupportInfo { get; set; }

    public string Description { get; set; }

    public int StatusId { get; set; }

    public Guid CreatedUserId { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime LastUpdatedDate { get; set; }

    public Guid LastUpdatedUserId { get; set; }
}